fix formatting

diff --git a/.local/share/scripts/spectacle b/.local/share/scripts/spectacle
--- a/.local/share/scripts/spectacle
+++ b/.local/share/scripts/spectacle
@@ -1,22 +1,22 @@
 #!/bin/sh
 
 if [ $# -ne 1 ]; then
-	printf "%s\n" "Wrong argument count: $#, required 1" >&2
-	exit
+    printf "%s\n" "Wrong argument count: $#, required 1" >&2
+    exit
 fi
 
 case $1 in
     full)
-		message="Fullscreen" ;;
+        message="Fullscreen" ;;
     window)
         args="a"
-		message="Active window" ;;
+        message="Active window" ;;
     rectangle)
         args="r"
-		message="Rectangle" ;;
-	*)
-		printf "%s\n" "unsupported argument '$1'" >&2
-		exit ;;
+        message="Rectangle" ;;
+    *)
+        printf "%s\n" "unsupported argument '$1'" >&2
+        exit ;;
 esac
 
 screenshot="${TMPDIR:-/tmp}/screenshot.png"
